# Probability distribution {.unnumbered}

**Instance of**: function

**AKA**: 

**Distinct from**: 

**English**: A probability distribution is a function that assigns probabilities to events. A normal distribution, beta distribution, and gamma distribution, for example, are all probability distributions.

There are three Kolmogorov axioms that a probability function must meet.

1. Probability of every event must be nonnegative.

2. No probability must exceed 1.

3. The probability of either of two disjoint events occurring must equal the sum of each of their individual probabilities of occuring.


Do not confuse a random variable for its distribution. A probability distribution is mathematical description of the long run behavior of a process, and a random variable may be usefully described by a existing well known probability distribution [@rossIntroductionProbabilitySimulation2022].

**Formalization**:

It's a function
$$ 
P: \mathcal{A} \mapsto \mathbb{R}
$$

::: {.column-margin}
Where $A$ is the input space, similar to a sample space.
:::


The three Kolmogorov axioms are formalized as

Axiom 1
$$ 
P(X \in E) \geq 0 \forall  E\in A
$$

Axiom 2
$$
P(X \in E) \leq 1 \forall  E\in A
$$

Axiom 3
$$
P(X \in \bigsqcup_{i \in I} \ E_i) = \sum_i P(X\in E_i)
$$

::: {.column-margin}
Where $\bigsqcup$ is the symbol for [disjoint union](https://en.wikipedia.org/wiki/Disjoint_union).
:::

    
**Cites**: [Wikipedia](https://en.wikipedia.org/wiki/Probability_density_function) ; [Wikidata]() ; [Wolfram]()

[Chapter 4 Distributions](https://bookdown.org/kevin_davisross/probsim-book/distchap.html)[@rossIntroductionProbabilitySimulation]
