project:
  type: book
  output-dir: docs


book:
  search: true
  repo-url: https://github.com/rexdouglass/IntroToAppliedScience
  repo-actions: [source]
  repo-branch: master
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  title: "Introduction to Applied Science"
  author: "Rex W. Douglass"
  date: "11/4/2022"
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - intro.qmd
        - lit.qmd
    - part: "Computation"
      chapters:
        - computation.qmd
        - R.qmd
    - part: "Research Design"
      chapters:
        - domain.qmd
        - outliers.qmd
        - estimand.qmd
        - identification.qmd
        - rct.qmd
        - iv.qmd
        - diffindiff.qmd
    - part: "Estimation"    
    - part: "Mathematical Objects"
      chapters:
        - set.qmd
        - list.qmd
        - tensor.qmd
        - table.qmd
    - part: "Operations of Arithmetic"
      chapters:
        - add.qmd
        - subtract.qmd
        - multiply.qmd
        - divide.qmd
    - part: "Operations of Algebra"
      chapters:
        - dotproduct.qmd    
    - part: "Moments of a Distribution"
      chapters:
        - mean.qmd
    - part: "Supervised Learning"
      chapters:
        - ols.qmd
        - decisiontree.qmd
        - randomforest.qmd
        - gradientboosted.qmd
    - part: "Unsupervised Learning"
      chapters:
        - distancemetrics.qmd
    - references.qmd

bibliography: IntroToAppliedScience.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



