project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Applied Science"
  author: "Rex W. Douglass"
  date: "11/4/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - mean.qmd
    - references.qmd

bibliography: IntroToAppliedScience.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



