project:
  type: book
  output-dir: docs


book:
  search: true
  repo-url: https://github.com/rexdouglass/IntroToAppliedScience
  repo-actions: [source]
  repo-branch: master
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  title: "Introduction to Applied Science"
  author: "Rex W. Douglass"
  date: "11/4/2022"
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - intro.qmd
        - lit.qmd
        - sociologyofinference.qmd
        - practicecoding.qmd
    - part: "Presentation"
      chapters:
        - markdown.qmd
    - part: "Computation"
      chapters:
        - computation.qmd
        - bash.qmd
        - R.qmd
        - python.qmd
        - jax.qmd
        - numpyro.qmd
        - stan.qmd
        - pytorch.qmd
        - tensorflow.qmd
        - sql.qmd
    - part: "Data management"
      chapters:
        - filter.qmd
        - joins.qmd
        - regex.qmd
        - fuzzyrecordmatching.qmd
    - part: "Domain"
      chapters:
        - domain.qmd
        - outliers.qmd
        - regimechange.qmd
        - poststratification.qmd
    - part: "Research Design"
      chapters:
        - projectdesign.qmd 
        - unitofanalysis.qmd
        - estimand.qmd
        - identification.qmd
        - GardenOfForkingPaths.qmd
        - rct.qmd
        - iv.qmd
        - diffindiff.qmd
        - biasvariancetradeoff.qmd
        - placebotests.qmd
    - part: "Estimation"
      chapters:
        - performance.qmd
        - outofsampleperformance.qmd
        - regularization.qmd
        - pvalues.qmd
    - part: "Mathematical Objects"
      chapters:
        - set.qmd
        - list.qmd
        - tensor.qmd
        - table.qmd
    - part: "Operations of Arithmetic"
      chapters:
        - add.qmd
        - subtract.qmd
        - multiply.qmd
        - divide.qmd
    - part: "Operations of Algebra"
      chapters:
        - dotproduct.qmd    
    - part: "Moments of a Distribution"
      chapters:
        - mean.qmd
    - part: "Supervised Learning"
      chapters:
        - ols.qmd
        - decisiontree.qmd
        - randomforest.qmd
        - gradientboosted.qmd
        - gaussianprocesses.qmd
    - part: "Unsupervised Learning"
      chapters:
        - distancemetrics.qmd
    - references.qmd

bibliography: IntroToAppliedScience.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



