
```{r}
install.packages('V8')
#library(V8)
#cx <- v8()
#cx$source("/home/skynet3/Downloads/twitter-2022-11-08-24fa1be25590defacf8df1fe45d475a1b82d1e6d6223a7c9cb10e61deff3c19d/data/tweets.js") # now the variable 'data' is defined #in V8
#cx$get("data") 

file="/home/skynet3/Downloads/twitter-2022-11-08-24fa1be25590defacf8df1fe45d475a1b82d1e6d6223a7c9cb10e61deff3c19d/data/tweets.js"
library(jsonlite)
df <- fromJSON(file)
names(df)
library(tidyverse)
tweets <- df$tweet %>% janitor::clean_names()
dim(tweets)
names(tweets)

tweets$rex_rank <- as.numeric(tweets$retweet_count) + as.numeric(tweets$favorite_count)

extended_entities <- tweets$extended_entities$media
dim(extended_entities)

extended_entities <- tweets$entities$urls
dim(extended_entities)

tweets$url <- sapply(tweets$entities$urls, FUN=function(x) { ifelse(is.null(x$expanded_url), NA, x$expanded_url) } ) %>% unlist()

tweets_url <- tweets %>% filter(!is.na(url))
dim(tweets_url)

View(tweets_url)

tweets_url_small <- tweets_url %>% 
                    dplyr::select(created_at, full_text, rex_rank, url) %>%
                    filter(!url %>% str_detect("twitter")) %>%
                    arrange(desc(rex_rank), url) 
dim(tweets_url_small)

tweets_url_small %>% write.csv("/mnt/8tb_a/rwd_github_private/IntroToAppliedScience/git_ignore/temp.csv")

tweets_url_labeled <- read.csv("/mnt/8tb_a/rwd_github_private/IntroToAppliedScience/git_ignore/temp_labeled.csv") #%>% filter(keep %in% 1)
dim(tweets_url_labeled)
tweets_url_labeled_bk <- tweets_url_labeled
dim(tweets_url_labeled_bk)
tweets_url_labeled %>% 
  arrange(desc(rex_rank), url)  %>% filter(!duplicated(url)) %>% 
  filter(!url %>% str_detect("covid")) %>% 
  #dim() %>%
  write.csv("/mnt/8tb_a/rwd_github_private/IntroToAppliedScience/git_ignore/temp_labeled.csv", row.names = FALSE)


tweets_url_labeled <- read.csv("/mnt/8tb_a/rwd_github_private/IntroToAppliedScience/git_ignore/temp_labeled.csv") #%>% filter(keep %in% 1)
dim(tweets_url_labeled)
for(url in tweets_url_labeled$url[1401:1500]){browseURL(url=url)}


```

```{r}




```